name: geocoder
description: Forward and reverse geocoding.
version: 0.2.1
author: Alo√Øs Deniel<alois.deniel@gmail.com>
homepage: https://github.com/aloisdeniel/flutter_geocoder

environment:
    sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.aloisdeniel.geocoder
    pluginClass: GeocoderPlugin
